title: Javascripts Galore. <div align="right"><a href="https://github.com/Clicketyclick/javascriptsGalore" title="Source"><kbd>&lt;&gt;</kbd></a><a href=".." title="Up"><kbd>&#x2303;</kbd></a><a href="/" title="Home"><kbd>&#x1F3E0;</kbd></a></div>
description: Various Javascript snippets
