title: JavascriptsGalore                 <script async type="text/javascript">var REPO="JavascriptsGalore";</script><script async type="text/javascript" src="/topmenu.js"></script>
description: Various Javascript snippets
